server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: Gate-Way
          uri: https://github.com/johansel23/microservices
          search-paths: config-data
  application:
    name: config-service
